// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svqphhmccwkfyozsqpyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cXBoaG1jY3drZnlvenNxcHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjI2MzgsImV4cCI6MjA2NjIzODYzOH0.-80-gUxSkPpe6Cyb4tNowB9Qv84uQV7TbowaylNZ0bM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);